#IMAGEN MODELO
FROM eclipse-temurin:17.0.13_11-jdk

#INFORMAR EL PUERTO DONDE SE EJECUTA EL CONTENEDOR (SOLO INFORMATIVO)
EXPOSE 5000

#DEFINIR DIRECTORIO RAIZ
WORKDIR /root

#COPIAR Y PEGAR ARCHIVOS DENTRO DEL CONTENEDOR
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

# DESCARGAR LAS DEPENDENCIAS
RUN ./mvnw dependency:go-offline

#COPIAR CODIGO FUENTE
COPY ./src /root/src

#CONSTRUIR NUESTRA APLICACION Y SALTAR LOS TEST UNITARIOS
RUN ./mvnw clean install -DskipTests

#LEVANTAR NUESTRA APLICACION CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java","-jar","/root/target/Mano-0.0.1-SNAPSHOT.jar"]