spring.application.name=Mano
# GENERAL
server.port=8080
#es el pueto 8080
#para paginas en internet es el puerto 80, ya que por ahi entran
#
# DATABASE
spring.datasource.url=jdbc:mysql://localhost/Mano?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
spring.datasource.dbname=Mano
spring.datasource.username=root
spring.datasource.password=3Hermanos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.hbm2ddl.auto=updatedup

#drive de mysql